### ISSUE TITLE
Login Screen - Connect login to feed

### ISSUE THREAD

**Issue by illumimarty** [UCM-MHTeam/Phrasy#9]
**Must finish #6 before starting**

On `Main.storyboard`
- [x] Add a Feed View Controller, create a Cocoa Touch Class of the same name, add identifiers.
- [x] Embed a Navigation Bar and Tab Bar onto the FeedVC
- [x] Add a `CollectionView` on the FeedVC and make a 
- [x] Connect Login VC to Feed VC (navigation controller not the actual VC).

**Comment by jballo** [comment]
Could you clarify on "navigation controller not the actual VC" @illumimarty

**Comment by illumimarty** [comment]
> Could you clarify on "navigation controller not the actual VC" @illumimarty

Yes, I'm noting that since we would have a nav/tabbar controller connected to the `HomeViewController`, the segue from login would have to connect to the nav controller and NOT the `HomeViewController` itself. Was more of something to look out for
